# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# - task: S3Upload@1
  inputs:
    awsCredentials: 'AWS-connection'
    regionName: 'ap-south-1'
    bucketName: 'hy0470'
    globExpressions: '**'
    createBucket: true

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
